ARG ROS_IMAGE=rbc_dev_ros:latest
FROM ${ROS_IMAGE}

# We only want to update the build whenever the source code changes, or the way we build the code changes.
# Thus, we COPY in the minimum amount of files necessary to build the code.

# Copy in the source code
COPY src/ /home/developer/repo/src

# Ensure that developer has permissions for the repo directory and subdirectories
RUN sudo chown -R developer:developer /home/developer

# The ROS environment definition
COPY docker/ros_environment.sh /home/developer/repo/docker/ros_environment.sh

# The cache_deps script
COPY docker/prebuild.sh /home/developer/repo/docker/prebuild.sh

# Now, we can build the code by first sourcing the ROS environment, then sourcing the cache_deps script, the running the cache_deps bash function.
RUN /bin/bash -c "source /home/developer/repo/docker/ros_environment.sh && source /home/developer/repo/docker/prebuild.sh && cache_deps"