ARG ROS_IMAGE=rbc_dev_ros:latest
FROM ${ROS_IMAGE}

# We only want to update the build whenever the source code changes, or the way we build the code changes.
# Thus, we COPY in the minimum amount of files necessary to build the code.

# Copy in the source code
COPY src/ /home/developer/repo/src

# Ensure that developer has permissions for the repo directory and subdirectories
RUN sudo chown -R developer:developer /home/developer

RUN sudo apt-get update && sudo apt-get install -y \
    ros-humble-joint-state-publisher-gui \
    ros-humble-ign-ros2-control \
    ros-humble-octomap-msgs \
    ros-humble-pcl-ros \
    ros-humble-robot-localization \
    libeigen3-dev \
    ros-humble-libg2o \
    libopencv-dev \
    libyaml-cpp-dev \
    libsqlite3-dev \
    cmake \
    ros-humble-control-msgs \
    ros-humble-effort-controllers \
    ros-humble-gazebo-ros2-control \
    ros-humble-gazebo-ros \
    ros-humble-hardware-interface \
    ros-humble-joint-trajectory-controller \
    ros-humble-joint-state-broadcaster \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-velocity-controllers \
    libgoogle-glog-dev \
    libfcl-dev \
    ros-humble-octomap \
    ros-humble-ompl \
    ros-humble-behaviortree-cpp-v3 \
    ros-humble-controller-manager \
    ros-humble-ros2-control-test-assets \
    ros-humble-backward-ros \
    ros-humble-controller-interface \
    ros-humble-realtime-tools \
    ros-humble-generate-parameter-library \
    python3-pytest \
    ros-humble-rqt-robot-steering \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-camera-info-manager \
    && sudo rm -rf /var/lib/apt/lists/*

# # The ROS environment definition
# COPY docker/ros_environment.sh /home/developer/repo/docker/ros_environment.sh

# # The cache_deps script
# COPY docker/prebuild.sh /home/developer/repo/docker/prebuild.sh

# # Now, we can build the code by first sourcing the ROS environment, then sourcing the cache_deps script, the running the cache_deps bash function.
# RUN /bin/bash -c "source /home/developer/repo/docker/ros_environment.sh && source /home/developer/repo/docker/prebuild.sh && cache_deps"